package edu.eci.cosw.persistencia;
// Generated 20/09/2015 08:58:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name="Cliente")
public class Cliente  implements java.io.Serializable {


     private int idCliente;
     private String nombre;
     private String descripcion;
     private Set<Ensayo> ensayos = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(int idCliente, String nombre) {
        this.idCliente = idCliente;
        this.nombre = nombre;
    }
    public Cliente(int idCliente, String nombre, String descripcion, Set<Ensayo> ensayos) {
       this.idCliente = idCliente;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.ensayos = ensayos;
    }
   
     @Id 

    
    @Column(name="idCliente", unique=true, nullable=false)
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }

    
    @Column(name="Nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="Descripcion", length=1000)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cliente")
    public Set<Ensayo> getEnsayos() {
        return this.ensayos;
    }
    
    public void setEnsayos(Set<Ensayo> ensayos) {
        this.ensayos = ensayos;
    }




}


