package edu.eci.cosw.persistencia;
// Generated 20/09/2015 08:58:00 PM by Hibernate Tools 4.3.1

import java.sql.Time;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Establecimiento generated by hbm2java
 */


@Entity
@Table(name="Establecimiento")
public class Establecimiento  implements java.io.Serializable {


     private int idEstablecimiento;
     private String nombre;
     private String nit;
     private String descripcion;
     private String direccion;
     private Time horaInicio;
     private Time horaCierre;
     private double multa;
     private String localidad;
     private String telefono;
     private String cuenta;
     private Set<Instrumento> instrumentos = new HashSet(0);
     private Set<Sala> salas = new HashSet(0);

    public Establecimiento() {
    }

	
    public Establecimiento(int idEstablecimiento, String nombre, String nit, String direccion, Time horaInicio, Time horaCierre, double multa, String localidad, String telefono, String cuenta) {
        this.idEstablecimiento = idEstablecimiento;
        this.nombre = nombre;
        this.nit = nit;
        this.direccion = direccion;
        this.horaInicio = horaInicio;
        this.horaCierre = horaCierre;
        this.multa = multa;
        this.localidad = localidad;
        this.telefono = telefono;
        this.cuenta = cuenta;
    }
    public Establecimiento(int idEstablecimiento, String nombre, String nit, String descripcion, String direccion, Time horaInicio, Time horaCierre, double multa, String localidad, String telefono, String cuenta, Set<Instrumento> instrumentos, Set<Sala> salas) {
       this.idEstablecimiento = idEstablecimiento;
       this.nombre = nombre;
       this.nit = nit;
       this.descripcion = descripcion;
       this.direccion = direccion;
       this.horaInicio = horaInicio;
       this.horaCierre = horaCierre;
       this.multa = multa;
       this.localidad = localidad;
       this.telefono = telefono;
       this.instrumentos = instrumentos;
       this.salas = salas;
       this.cuenta = cuenta;
    }
   
     @Id 

    
    @Column(name="idEstablecimiento", unique=true, nullable=false)
    public int getIdEstablecimiento() {
        return this.idEstablecimiento;
    }
    
    public void setIdEstablecimiento(int idEstablecimiento) {
        this.idEstablecimiento = idEstablecimiento;
    }

    
    @Column(name="Nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="NIT", nullable=false, length=45)
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }

    
    @Column(name="Descripcion", length=1000)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="Direccion", nullable=false, length=45)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="HoraInicio", nullable=false)
    public Time getHoraInicio() {
        return this.horaInicio;
    }
    
    public void setHoraInicio(Time horaInicio) {
        this.horaInicio = horaInicio;
    }

    
    @Column(name="HoraCierre", nullable=false)
    public Time getHoraCierre() {
        return this.horaCierre;
    }
    
    public void setHoraCierre(Time horaCierre) {
        this.horaCierre = horaCierre;
    }

    
    @Column(name="Multa", nullable=false, precision=22, scale=0)
    public double getMulta() {
        return this.multa;
    }
    
    public void setMulta(double multa) {
        this.multa = multa;
    }

    
    @Column(name="Localidad", nullable=false, length=18)
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }

    
    @Column(name="Telefono", nullable=false, length=45)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    
    @Column(name="Cuenta", nullable=false, length=100)
    public String getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(String cuenta) {
        this.cuenta = cuenta;
    }    

@OneToMany(fetch=FetchType.LAZY, mappedBy="establecimiento")
    public Set<Instrumento> getInstrumentos() {
        return this.instrumentos;
    }
    
    public void setInstrumentos(Set<Instrumento> instrumentos) {
        this.instrumentos = instrumentos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="establecimiento")
    public Set<Sala> getSalas() {
        return this.salas;
    }
    
    public void setSalas(Set<Sala> salas) {
        this.salas = salas;
    }




}


