package edu.eci.cosw.persistencia;
// Generated 20/09/2015 08:58:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sala generated by hbm2java
 */
@Entity
@Table(name="Sala")
public class Sala  implements java.io.Serializable {


     private int idSala;
     private Establecimiento establecimiento;
     private String precio;
     private String descripcion;
     private String nombre;
     private Set<Reservacion> reservacions = new HashSet(0);

    public Sala() {
    }

	
    public Sala(int idSala, Establecimiento establecimiento, String precio, String nombre) {
        this.idSala = idSala;
        this.establecimiento = establecimiento;
        this.precio = precio;
        this.nombre = nombre;
    }
    public Sala(int idSala, Establecimiento establecimiento, String precio, String descripcion, String nombre, Set<Reservacion> reservacions) {
       this.idSala = idSala;
       this.establecimiento = establecimiento;
       this.precio = precio;
       this.descripcion = descripcion;
       this.nombre = nombre;
       this.reservacions = reservacions;
    }
   
     @Id 

    
    @Column(name="idSala", unique=true, nullable=false)
    public int getIdSala() {
        return this.idSala;
    }
    
    public void setIdSala(int idSala) {
        this.idSala = idSala;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Establecimiento_idEstablecimiento", nullable=false)
    public Establecimiento getEstablecimiento() {
        return this.establecimiento;
    }
    
    public void setEstablecimiento(Establecimiento establecimiento) {
        this.establecimiento = establecimiento;
    }

    
    @Column(name="Precio", nullable=false, length=45)
    public String getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(String precio) {
        this.precio = precio;
    }

    
    @Column(name="Descripcion", length=1000)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="Nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sala")
    public Set<Reservacion> getReservacions() {
        return this.reservacions;
    }
    
    public void setReservacions(Set<Reservacion> reservacions) {
        this.reservacions = reservacions;
    }




}


